server:
  port: 8083
  error:
    include-message: always

spring:
  application:
    name: favorites-service
    url: /public/api/v1/users/

  config:
    import: "optional:configserver:"

  jackson:
    serialization:
      fail-on-empty-beans: false

  jpa:
    database: POSTGRESQL
    show-sql: true
    generateDdl: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  datasource:
    url: jdbc:postgresql://localhost:5432/favorite
    username: postgres
    password: admin
    driverClassName: org.postgresql.Driver
    hikari:
      auto-commit: false

  flyway:
    enabled: true
    defaultSchema: public

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://51.250.102.12:9000/oauth2/jwks

  logging:
    level:
      web: DEBUG

management:
  tracing:
    enabled: false
    sampling:
      probability: 0.1
  endpoints:
    web:
      exposure:
        include: prometheus, health
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans