server:
  port: 8083
  error:
    include-message: always

spring:
  application:
    name: favorites-service
    url: /public/api/v1/users/

  config:
    import: "optional:configserver:"

  jackson:
    serialization:
      fail-on-empty-beans: false

  flyway:
    enabled: false
    defaultSchema: favorite

  jpa:
    database: POSTGRESQL
    show-sql: true
    generateDdl: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        schema_update:
          unique_constraint_strategy: RECREATE_QUIETLY
        connection:
          provider_disables_autocommit: true

  datasource:
    url: jdbc:postgresql://localhost:5432/favorite
    username: postgres
    password: admin
    driverClassName: org.postgresql.Driver
    hikari:
      auto-commit: false

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://51.250.102.12:9000/oauth2/jwks

  logging:
    level:
      web: DEBUG