server:
  port: 8083
  error:
    include-message: always

spring:
  application:
    name: favorites-service
    url: /public/api/v1/users/

  config:
    import: "optional:configserver:"

  jackson:
    serialization:
      fail-on-empty-beans: false

  flyway:
    enabled: false

  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        schema_update:
          unique_constraint_strategy: RECREATE_QUIETLY
        connection:
          provider_disables_autocommit: true

  datasource:
    url: jdbc:postgresql://localhost:5432/favorite
    username: postgres
    password: admin
    driverClassName: org.postgresql.Driver
    hikari:
      auto-commit: false