app:
  users-api:
    path: /public/api/v1/users
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/user_info_db4
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver