spring:
  jpa:
    show-sql: false
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: validate
    properties:
      hibernate:
        generate_statistics: false
        format_sql: false

  data:
    redis:
      host: redis
      port: 6379
      password: password

  cache:
    type: redis

  datasource:
    url: jdbc:postgresql://postgres:5432/test2
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver

app:
  validation:
    error-info:
      INCORRECT_FIRST_NAME_CODE: 'Incorrect format firstname: %s'
      INCORRECT_LAST_NAME_CODE: 'Incorrect format lastname'
      INCORRECT_EMAIL_CODE: 'Incorrect format email: %s'
      BLANK_EMAIL_CODE: 'Email can not be blank'
      BLANK_BIRTHDAY_CODE: 'Birthday can not be blank!'
      BLANK_FIRST_NAME_CODE: 'Firstname can not be blank'
      BLANK_LAST_NAME_CODE: 'Lastname can not be blank'
      BLANK_PASSWORD_CODE: 'Password can not be blank'
      BLANK_PHONE_CODE: 'Phone can not be blank'
      NULL_SEX_CODE: 'Sex should not be null'
