spring:
  jpa:
    show-sql: true
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: validate
    properties:
      hibernate:
        generate_statistics: true
        format_sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/${DB_NAME}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

app:
  validation:
    error-info:
      BLANK_FIRST_NAME_VALIDATION_ERROR_CODE: 'Firstname can not be blank'
      BLANK_LAST_NAME_VALIDATION_ERROR_CODE: 'Lastname can not be blank'
      BLANK_EMAIL_VALIDATION_ERROR_CODE: 'Email can not be blank'
      BLANK_PASSWORD_VALIDATION_ERROR_CODE: 'Password can not be blank'
      BLANK_PHONE_VALIDATION_ERROR_CODE: 'Phone can not be blank'
      BLANK_BIRTHDAY_VALIDATION_ERROR_CODE: 'Birthday can not be blank'
      INCORRECT_FIRST_NAME_VALIDATION_ERROR_CODE: 'Incorrect firstname format: %s'
      INCORRECT_LAST_NAME_VALIDATION_ERROR_CODE: 'Incorrect lastname format: %s'
      INCORRECT_PHONE_VALIDATION_ERROR_CODE: 'Incorrect format for phone number: %s'
      INCORRECT_EMAIL_VALIDATION_ERROR_CODE: 'Incorrect email format: %s'
      INCORRECT_PASSWORD_VALIDATION_ERROR_CODE: 'Incorrect password format: %s. The correct password should contain:[at least 1 uppercase letter, at least 1 lowercase letter, at least 1 number, at least 1 special character]. Minimum 8 characters and maximum 30 characters.'