package com.yandex.market.userinfoservice.utils;

import lombok.experimental.UtilityClass;

@UtilityClass
public class ValidationCodeConstants {
    public String BLANK_FIRST_NAME_VALIDATION_ERROR_CODE = "BLANK_FIRST_NAME_VALIDATION_ERROR_CODE";
    public String BLANK_LAST_NAME_VALIDATION_ERROR_CODE = "BLANK_LAST_NAME_VALIDATION_ERROR_CODE";
    public String BLANK_EMAIL_VALIDATION_ERROR_CODE = "BLANK_EMAIL_VALIDATION_ERROR_CODE";
    public String BLANK_PASSWORD_VALIDATION_ERROR_CODE = "BLANK_PASSWORD_VALIDATION_ERROR_CODE";
    public String BLANK_PHONE_VALIDATION_ERROR_CODE = "BLANK_PHONE_VALIDATION_ERROR_CODE";
    public String BLANK_BIRTHDAY_VALIDATION_ERROR_CODE = "BLANK_BIRTHDAY_VALIDATION_ERROR_CODE";
    public String INCORRECT_FIRST_NAME_VALIDATION_ERROR_CODE = "INCORRECT_FIRST_NAME_VALIDATION_ERROR_CODE";
    public String INCORRECT_LAST_NAME_VALIDATION_ERROR_CODE = "INCORRECT_LAST_NAME_VALIDATION_ERROR_CODE";
    public String INCORRECT_EMAIL_VALIDATION_ERROR_CODE = "INCORRECT_EMAIL_VALIDATION_ERROR_CODE";
    public String INCORRECT_PASSWORD_VALIDATION_ERROR_CODE = "INCORRECT_PASSWORD_VALIDATION_ERROR_CODE";
    public String INCORRECT_PHONE_VALIDATION_ERROR_CODE = "INCORRECT_PHONE_VALIDATION_ERROR_CODE";
}