spring:
  kafka:
    bootstrap-servers: localhost:9092

  cloud:
    config:
      enabled: false

  datasource:
    url: jdbc:postgresql://localhost:5432/test
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: false