server:
  port: 8081

spring:
  jackson:
    serialization:
      fail-on-empty-beans: false
  flyway:
    baseline-on-migrate: true
  jpa:
    show-sql: true
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: create
    properties:
      hibernate:
#        generate_statistics: true
        format_sql: true
#        hbm2ddl:
#          auto: create
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:navvrks9}
    driver-class-name: org.postgresql.Driver

