server:
  port: 8081

spring:
  application:
    name: order-service
  jackson:
    serialization:
      fail-on-empty-beans: false
  config:
    import: "optional:configserver:"
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/order_db}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:123}
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: false

management:
  tracing:
    enabled: false
    sampling:
      probability: 0.1
  endpoints:
    web:
      exposure:
        include: prometheus, health
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans