spring:
  app:
    shops:
      url: /public/api/v1/
    product-controller:
      url: /public/api/v1/products

  datasource:
    url: jdbc:postgresql://51.250.102.12:5432/test2
    username: user
    password: password
    driverClassName: org.postgresql.Driver
    hikari:
      auto-commit: false

  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update # далее validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        schema_update:
          unique_constraint_strategy: RECREATE_QUIETLY
        connection:
          provider_disables_autocommit: true
    open-in-view: false

  flyway:
    enabled: false
