server:
  port: 9090

spring:
  flyway:
    enabled: false #  дальше убрать эту и строку повыше
  app:
    product:
      url: /public/api/v1/products/
    seller:
      url: /public/api/v1/sellers/

  datasource:
    url: jdbc:postgresql://localhost:5432/${DB_NAME}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update # далее validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
#        schema_update:
#          unique_constraint_strategy: RECREATE_QUIETLY
#        connection:
#          provider_disables_autocommit: true

