server:
  port: 9090

spring:
  application:
    name: product-service
  flyway:
    enabled: false
  app:
    product:
      url: /public/api/v1/products/
    seller:
      url: /public/api/v1/sellers/

  datasource:
    url: jdbc:postgresql://localhost:5432/test
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver

  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop # далее validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
#  data:
#    redis:
#      jedis:
#        pool:
#          enabled: false
#      host: 51.250.102.12
#      port: 6379
#      database: 0

  kafka:
    bootstrap-servers: localhost:9092


