server:
  port: 9090

spring:
  flyway:
    enabled: false
  app:
    product:
      url: /public/api/v1/products/
    seller:
      url: /public/api/v1/sellers/

  datasource:
    url: jdbc:postgresql://51.250.102.12:5432/${DB_NAME}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update # далее validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  data:
    redis:
      jedis:
        pool:
          enabled: false
      host: 51.250.102.12
      port: 6379
      database: 0