server:
  port: 9090

spring:
  application:
    name: product-service
  flyway:
    enabled: false

  config:
    import: "optional:configserver:"

  datasource:
    url: jdbc:postgresql://${DB_URL}:5432/${DB_NAME}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update # далее validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  data:
    redis:
      jedis:
        pool:
          enabled: false
      host: 51.250.102.12
      port: 6379
      database: 0

  kafka:
    bootstrap-servers: localhost:9092