server:
  port: 9090


spring:
  application:
    name: product-service
  flyway:
    enabled: true

  config:
    import: "optional:configserver:"

  datasource:
    url: jdbc:postgresql://localhost:32768/product
    username: postgres
    password: postgrespw
    driver-class-name: org.postgresql.Driver

  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: validate # далее validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  data:
    redis:
      jedis:
        pool:
          enabled: false
      host: 51.250.102.12
      port: 6379
      database: 0

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://127.0.0.1:9000/oauth2/jwks


  kafka:
    bootstrap-servers: localhost:9092

logging:
  level:
    web: DEBUG