server:
  port: 9090


spring:
  application:
    name: product-service
  flyway:
    enabled: false

  config:
    import: "optional:configserver:"

  datasource:
    url: jdbc:postgresql://158.160.27.104:5432/product_db
    username: user
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: validate # далее validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  data:
    redis:
      jedis:
        pool:
          enabled: false
      host: 51.250.102.12
      port: 6379
      database: 0

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://51.250.102.12:9000/oauth2/jwks

  kafka:
    bootstrap-servers: localhost:9092

management:
  tracing:
    enabled: false
    sampling:
      probability: 0.1
  endpoints:
    web:
      exposure:
        include: prometheus, health
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans

logging:
  level:
    web: DEBUG