-- INSERT 5 DATA FIXTURES
INSERT INTO users (id,
                  birthday,
--                  created_at,
                  email,
                  external_id,
                  first_name,
                  is_deleted,
                  last_name,
                  apartment_number,
                  city,
                  country,
                  house_number,
                  postcode,
                  region,
                  street,
                  login,
                  middle_name,
                  modified_at,
                  is_allowed_to_receive_on_address,
                  is_allowed_to_send_discounts_and_promotions_mailing_lists,
                  is_allowed_to_send_popular_articles,
                  password,
                  phone,
                  photo_id,
                  sex)
    VALUES (1,
            '2001-01-01',
--            '2023-01-18 11:52:38.59412'
            'test_mail@gmail.com',
            'f34c4cd3-6fe7-4d3e-b82c-f5d044e46091',
            'firstName',
            false,
            'lastName',
            '12',
            'Saint-Petersburg',
            'Russia',
            '5',
            '192281',
            'Florida',
            'Ocean Drive',
            'test_login',
            'middleName',
            '2023-01-18 11:52:38.59412',
            true,
            true,
            true,
            'TestPassword1!',
            '+7 (924) 124-95-21',
            'id2003104u48396',
            'MALE');
--INSERT INTO USER (id, name, email) VALUES (2, 'Camille Guérin', 'rayan.sanchez@yahoo.fr');
--INSERT INTO USER (id, name, email) VALUES (3, 'Julien Mael', 'laura.royer@yahoo.fr');
--INSERT INTO USER (id, name, email) VALUES (4, 'Gérard Mael', 'victor.dupuis@hotmail.fr');
--INSERT INTO USER (id, name, email) VALUES (5, 'Dubois Anaïs', 'alice.lemoine@hotmail.fr');