package com.yandex.market.userservice.utils;

import lombok.experimental.UtilityClass;

@UtilityClass
public class ValidationCodeConstants {
    public static String BLANK_EMAIL_VALIDATION_ERROR_CODE = "BLANK_EMAIL_VALIDATION_ERROR_CODE";
    public static String BLANK_PASSWORD_VALIDATION_ERROR_CODE = "BLANK_PASSWORD_VALIDATION_ERROR_CODE";
    public static String INCORRECT_FIRST_NAME_VALIDATION_ERROR_CODE = "INCORRECT_FIRST_NAME_VALIDATION_ERROR_CODE";
    public static String INCORRECT_LAST_NAME_VALIDATION_ERROR_CODE = "INCORRECT_LAST_NAME_VALIDATION_ERROR_CODE";
    public static String INCORRECT_EMAIL_VALIDATION_ERROR_CODE = "INCORRECT_EMAIL_VALIDATION_ERROR_CODE";
    public static String INCORRECT_PASSWORD_VALIDATION_ERROR_CODE = "INCORRECT_PASSWORD_VALIDATION_ERROR_CODE";
    public static String INCORRECT_PHONE_VALIDATION_ERROR_CODE = "INCORRECT_PHONE_VALIDATION_ERROR_CODE";
    public static String INCORRECT_MIDDLE_NAME_VALIDATION_ERROR_CODE = "INCORRECT_MIDDLE_NAME_VALIDATION_ERROR_CODE";
    public static String INCORRECT_SEX_TYPE_ERROR_CODE = "INCORRECT_SEX_TYPE_ERROR_CODE";
}