server:
  port: 8080

spring:
  application:
    name: shop_system
    url: public/api/v1/shopsystems
  datasource:
    url: jdbc:postgresql://localhost:5432/${db_name}
    username: ${postgres_user}
    password: ${postgres_password}
    driverClassName: org.postgresql.Driver
    hikari:
      auto-commit: false
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update # далее validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        shema_update:
          unique_constraint_strategy: RECREATE_QUIETLY
        connection:
          provider_disables_autocommit: true

  flyway:
    enabled: false