server:
  port: 8080
  error:
    include-message: always

spring:
  application:
    name: shop_system
    url:
      shop: public/api/v1/shopsystems
      branch: public/api/v1/
  datasource:
    url: jdbc:postgresql://localhost:5432/${DB_NAME}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driverClassName: org.postgresql.Driver
    hikari:
      auto-commit: false
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update # далее validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        schema_update:
          unique_constraint_strategy: RECREATE_QUIETLY
        connection:
          provider_disables_autocommit: true

  flyway:
    enabled: false