server:
  port: 8080

spring:
  application:
    name: shop_system
  datasource:
    url: jdbc:postgresql://localhost:5432/shop_system
    username: damir
    password: damir
    driverClassName: org.postgresql.Driver
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update # далее validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true