application:
  extension:
    jpg:
      max_file_size_in_bytes: 153600
    png:
      max_file_size_in_bytes: 1000000
    pdf:
      max_file_size_in_bytes: 50000
  validation:
    maximum_files_count: 5
  object-storage:
    host: storage.yandexcloud.net
    region: ru-central1
    bucket-name: marketplace-object-storage
    credentials:
      secret-key: ${SECRET_KEY}
      access-key: ${ACCESS_KEY}
    url-expiration-time-in-minutes: 525600 # 1 year

spring:
  application:
    name: upload-service
  config:
    import: optional:configserver:http://localhost:8888
  data:
    mongodb:
      uri: mongodb://localhost:27017/upload-service
      database: upload-service

management:
  endpoints:
    web:
      exposure:
        include: prometheus,health
  metrics:
    tags:
      application: ${spring.application.name}
  server:
    port: 9001
    ssl:
      enabled: false

logging:
  level:
    org:
      springframework:
        web:
          filter:
            CommonsRequestLoggingFilter: DEBUG