application:
  object-storage:
    host: storage.yandexcloud.net
    region: ru-central1
    bucket-name: marketplace-object-storage
    credentials:
      secret-key: YCM_cp6q_WfD97OPLsAXsVT5eVxEiO7Qma_0jMfE
      access-key: YCAJEed9o_kAS76-bPBVqqrte

spring:
  application:
    name: upload-service

server:
  port: 9001