server:
  port: 9001


application:
  validation:
    max_uploaded_files_count: 10
    max_downloaded_files_count: 10
    extension:
      jpg:
        max_file_size_in_bytes: 10_485_760 #10 mb
        file_types:
          - AVATAR
          - PRODUCT
      jpeg:
        max_file_size_in_bytes: 10_485_760 #10 mb
        file_types:
          - AVATAR
          - PRODUCT
      png:
        max_file_size_in_bytes: 10_485_760 #10 mb
        file_types:
          - AVATAR
          - PRODUCT
      heif:
        max_file_size_in_bytes: 10_485_760 #10 mb
        file_types:
          - AVATAR
          - PRODUCT
      gif:
        max_file_size_in_bytes: 10_485_760 #10 mb
        file_types:
          - AVATAR
          - PRODUCT
      webp:
        max_file_size_in_bytes: 10_485_760 #10 mb
        file_types:
          - AVATAR
          - PRODUCT
      mov:
        max_file_size_in_bytes: 10_485_760 #10 mb
        file_types:
          - PRODUCT
      mp4:
        max_file_size_in_bytes: 10_485_760 #10 mb
        file_types:
          - PRODUCT
      mkv:
        max_file_size_in_bytes: 10_485_760 #10 mb
        file_types:
          - PRODUCT
      m4v:
        max_file_size_in_bytes: 10_485_760 #10 mb
        file_types:
          - PRODUCT
      avi:
        max_file_size_in_bytes: 10_485_760 #10 mb
        file_types:
          - PRODUCT
      pdf:
        max_file_size_in_bytes: 5_242_880 #5 mb
        file_types:
          - CHECK


  object-storage:
    host: storage.yandexcloud.net
    region: ru-central1
    bucket_name: marketplace-object-storage
    credentials:
      secret-key: ${SECRET_KEY}
      access-key: ${ACCESS_KEY}
    url_expiration_time_in_years: 1

spring:
  servlet:
    multipart:
      enabled: true
  application:
    name: upload-service
  config:
    import: optional:configserver:http://localhost:8888
  data:
    mongodb:
      uri: mongodb://localhost:27023/upload_service
      database: upload_service

management:
  endpoints:
    web:
      exposure:
        include: prometheus,health
  metrics:
    tags:
      application: ${spring.application.name}
  server:
    port: 9001
    ssl:
      enabled: false

logging:
  level:
    org:
      springframework:
        web:
          filter:
            CommonsRequestLoggingFilter: DEBUG