application:
  object-storage:
    host: storage.yandexcloud.net
    region: ru-central1
    bucket-name: marketplace-object-storage
    credentials:
    expiration-time: 60 # in minutes

spring:
  application:
    name: upload-service

server:
  port: 9001