application:
  extension:
    jpg:
      max_file_size_in_bytes: 153600
    png:
      max_file_size_in_bytes: 1000000
    pdf:
      max_file_size_in_bytes: 50000
  validation:
    maximum_files_count: 5
  object-storage:
    host: storage.yandexcloud.net
    region: ru-central1
    bucket-name: marketplace-object-storage
    credentials:
    expiration-time: 60 # in minutes

spring:
  application:
    name: upload-service
  config:
    import: optional:configserver:http://localhost:8888

server:
  port: 9001

logging:
  level:
    org:
      springframework:
        web:
          filter:
            CommonsRequestLoggingFilter: DEBUG