application:
  extension:
    jpg:
      max_file_size_in_bytes: 153600
    png:
      max_file_size_in_bytes: 1000000
    pdf:
      max_file_size_in_bytes: 50000
  validation:
    maximum_files_count: 5
  object-storage:
    host: storage.yandexcloud.net
    region: ru-central1
    bucket-name: marketplace-object-storage
    credentials:
      secret-key: ${SECRET_KEY}
      access-key: ${ACCESS_KEY}
    expiration-time: 60 # in minutes

spring:
  application:
    name: upload-service
  config:
    import: optional:configserver:http://localhost:8888
  data:
    mongodb:
      uri: mongodb://localhost:27017/upload-service
      database: upload-service

management:
  tracing:
    enabled: false
    sampling:
      probability: 0.1
  endpoints:
    web:
      exposure:
        include: prometheus,health
  metrics:
    tags:
      application: ${spring.application.name}

logging:
  level:
    org:
      springframework:
        web:
          filter:
            CommonsRequestLoggingFilter: DEBUG