openapi: 3.0.3
info:
  title: Swagger User-Info Serivce - OpenAPI 3.0
  version: 0.0.1
  description: |-
    Developed by Vlad, Arkady and Andrey
    
    Some useful links:
    - [User Info Github Repository](https://github.com/splendid-pdf/yandex-market/tree/master/user-info-service)

servers:
  - url: http://localhost:8080/public/api/v1
tags:
  - name: user
    description: Rest API service to CRUD user's information
paths:
  /users:
    post:
      tags:
        - user
      summary: Create user
      operationId: createUser
      requestBody:
        description: JSON Object with user's information
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserRequestDto'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: string
                format: uuid
                example: 'b0ca32a7-6960-49a9-9f20-d78fb3799409'

        '400':
          description: Invalid data provided to the server
    get:
      tags:
        - user
      summary: Get user by email or phone
      operationId: getUserByEmailOrPhone
      parameters:
        - in: query
          name: emailOrPhone
          schema: {
            type: string
          }
          description: The provided user's email or phone
          required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResponseDto'
        '400':
          description: Invalid data provided to the server
        '404':
          description: User by email or phone {emailOrPhone} was not found
  /users/{externalId}:
    get:
      tags:
        - user
      summary: Get a user by external id
      operationId: getByExternalId
      parameters:
        - in: path
          name: externalId
          description: User External Id
          schema: {
            type: string,
            format: uuid
          }
          example: 'b0ca32a7-6960-49a9-9f20-d78fb3799409'
          required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResponseDto'
        '400':
          description: Invalid data provided to the server
        '404':
          description: User by id {externalId} was not found
    put:
      tags:
        - user
      summary: Update user
      description: This can only be done by the logged in user.
      operationId: updateUser
      parameters:
        - name: externalId
          in: path
          description: user external id
          required: true
          schema: {
            type: string,
            format: uuid
          }
      requestBody:
        description: Update an existent user
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserRequestDto'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResponseDto'
        '400':
          description: Invalid data provided to the server
        '404':
          description: User by id {externalId} was not found
    delete:
      tags:
        - user
      summary: Delete user
      description: This can only be done by the logged in user.
      operationId: deleteUser
      parameters:
        - in: path
          name: externalId
          description: User External Id
          schema: {
            type: string,
            format: uuid
          }
          example: 'b0ca32a7-6960-49a9-9f20-d78fb3799409'
          required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResponseDto'
        '400':
          description: Invalid username supplied
        '404':
          description: User not found
  /users/{externalId}/location:
    get:
      tags:
        - user
      summary: Get a user's location by external id
      operationId: getUserLocationByExternalId
      parameters:
        - in: path
          name: externalId
          description: User External Id
          schema: {
            type: string,
            format: uuid
          }
          example: 'b0ca32a7-6960-49a9-9f20-d78fb3799409'
          required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Location'
        '400':
          description: Invalid data provided to the server
        '401':
          description: Unauthorized request
        '403':
          description: No permissions to perform that request
        '404':
          description: User by id {externalId} was not found
components:
  schemas:
    NotificationSettings:
      type: object
      properties:
        isAllowedToReceiveOnAddress:
          type: boolean
          default: true
          example: true
        isAllowedToSendPromotionsAndMailingLists:
          type: boolean
          default: true
          example: true
        isAllowedToSendPopularArticles:
          type: boolean
          default: true
          example: true
    UserRequestDto:
      required:
        - email
        - password
      type: object
      properties:
        firstName:
          type: string
          example: John
        middleName:
          type: string
          example:
        lastName:
          type: string
          example: Thompson
        phone:
          type: string
          example: '+79241249521'
        email:
          type: string
          example: john-thompson@email.com
        password:
          type: string
          example: 'I_AMfr0mSpb259631!@#'
        birthday:
          type: string
          format: date
          description: Date of birth
          example: 1967-01-02
        sex:
          type: string
          enum:
            - MALE
            - FEMALE
            - NONE
        location:
          $ref: '#/components/schemas/Location'
        contacts:
          type: array
          items:
            $ref: '#/components/schemas/Contact'
        notificationSettings:
          $ref: '#/components/schemas/NotificationSettings'
        photoId:
          type: string
          example: 'id2003104u48396'
    UserResponseDto:
      required:
        - email
        - password
      type: object
      properties:
        firstName:
          type: string
          example: John
        middleName:
          type: string
          example:
        lastName:
          type: string
          example: Thompson
        phone:
          type: string
          example: '+79241249521'
        email:
          type: string
          example: john-thompson@email.com
        birthday:
          type: string
          format: date
          description: Date of birth
          example: 1967-01-02
        sex:
          type: string
          enum:
            - MALE
            - FEMALE
            - NONE
        location:
          $ref: '#/components/schemas/Location'
        contacts:
          type: array
          items:
            $ref: '#/components/schemas/Contact'
        notificationSettings:
          $ref: '#/components/schemas/NotificationSettings'
        photoId:
          type: string
          example: 'id2003104u48396'
    Location:
      type: object
      properties:
        country:
          type: string
          example: 'USA'
        region:
          type: string
          example: 'Florida'
        city:
          type: string
          example: 'Saint-Petersburg'
        postcode:
          type: string
          example: '33112'
        street:
          type: string
          example: 'Ocean Drive'
        houseNumber:
          type: integer
          format: int32
          example: 5
        apartNumber:
          type: integer
          format: int32
          example: 12
    Contact:
      type: object
      properties:
        value:
          type: string
          example: "vk.com/id153215112412"
        type:
          type: string
          enum:
            - VK
            - TWITTER
            - FACEBOOK
            - TELEGRAM
            - INSTAGRAM
  requestBodies:
    User:
      description: User object that needs to be added to the database
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/UserRequestDto'
    UserArray:
      description: List of user object
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/UserRequestDto'