server:
  port: 9091

spring:
  application:
    name: basket-service
  flyway:
    enabled: true

  datasource:
    url: jdbc:postgresql://localhost:5432/basket_db
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver

  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://51.250.102.12:9000/oauth2/jwks