server:
  port: 7777

spring:
  application:
    name: api-gateway-service
  config:
    import: "optional:configserver:"
  security:
    oauth2:
      client:
        registration:
            myoauth2:
              provider: spring
              client-id: client
              client-secret: secret
              authorization-grant-type: authorization_code
              redirect-uri: http://127.0.0.1:7777/login/oauth2/code/myoauth2
              scope: openid
              client-name: myoauth2
              client-authentication-method: client-secret-basic

        provider:
          spring:
            issuer-uri: http://localhost:9000


  cloud:
    gateway:
      routes:
        - id: order-service-route
          uri: http://localhost:8081
          predicates:
            - Path=/*/*/*/orders, /*/*/*/orders/**
        - id: user-info-service-route
          uri: http://localhost:8080
          predicates:
            - Path=/*/*/*/users, /*/*/*/users/{externalId}, /*/*/*/users/search
        - id: product-service-route
          uri: http://localhost:9090
          predicates:
            - Path=/*/*/*/products, /*/*/*/products/{externalId}, /*/*/*/products/search, /*/*/*/*/*/products, /*/*/*/*/*/products/categories, /*/*/*/*/*/products/categories/**, /*/*/*/*/*/products/search/by-name
        - id: favorite-service-route
          uri: http://localhost:8082
          predicates:
            - Path=/*/*/*/*/*/favorites, /*/*/*/*/*/favorites/{externalId}
management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: gateway

logging:
  level:
    web: DEBUG