server:
  port: 7777

spring:
  application:
    name: api-gateway-service
  config:
    import: "optional:configserver:"
  cloud:
    gateway:
      routes:
        - id: order-service-route
          uri: http://127.0.0.1:8081
          predicates:
            - Path=/*/*/*/orders, /*/*/*/orders/**
        - id: user-info-service-route
          uri: http://127.0.0.1:8080
          predicates:
            - Path=/*/*/*/users, /*/*/*/users/{externalId}
        - id: product-service-route
          uri: http://127.0.0.1:9090
          predicates:
            - Path=/*/*/*/products, /*/*/*/products/{externalId}, /*/*/*/products/search, /*/*/*/*/*/products, /*/*/*/*/*/products/categories, /*/*/*/*/*/products/categories/**, /*/*/*/*/*/products/search/by-name, /*/*/*/*/{sellerId}/products, /*/*/*/*/{sellerId}/products/**, /*/*/*/*/{sellerId}/products/{productId}, /*/*/*/*/{sellerId}/products/{productId}/**, /*/*/*/*/{sellerId}/products/special-prices/{specialPriceId}, /*/*/*/*/{sellerId}/products/characteristics/{characteristicId}, /*/*/*/product-previews, /*/*/*/*/{sellerId}/archive/products,
        - id: favorite-service-route
          uri: http://127.0.0.1:8082
          predicates:
            - Path=/*/*/*/*/*/favorites, /*/*/*/*/*/favorites/{externalId}
        - id: upload-service-route
          uri: http://127.0.0.1:9001
          predicates:
            - Path=/*/*/*/files
        - id: review-service
          uri: http://127.0.0.1:8083
          predicates:
            - Path=/*/*/*/users/{userId}/reviews, /*/*/*/products/{productId}/reviews, /*/*/*/users/reviews/{reviewId}
        - id: seller-service
          uri: http://127.0.0.1:8085
          predicates:
            - Path=/*/*/*/sellers, /*/*/*/sellers/{externalId}
      default-filters:
        - name: AuthFilter

  security:
    oauth2:
      client:
        registration:
          custom-oidc:
            provider: custom-oidc
            scope: openid
            client-id: client
            client-secret: secret
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_basic
            redirect-uri: "http://127.0.0.1:7777/login/oauth2/code/custom-oidc"
        provider:
          custom-oidc:
            issuer-uri: "http://127.0.0.1:9000"
            token-uri: "http://127.0.0.1:9000/oauth2/token"
            authorization-uri: "http://127.0.0.1:9000/oauth2/authorize"
            jwk-set-uri: "http://127.0.0.1:9000/oauth2/jwks"
            user-info-uri: "http://127.0.0.1:9000/userinfo"

management:
  tracing:
    enabled: false
    sampling:
      probability: 0.1
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: gateway, prometheus
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans

application:
  security:
    white-list:
      # users-api
      - url: /*/*/*/users
        methods: POST
      # sellers-api
      - url: /*/*/*/sellers
        methods: POST
      - url: /*/*/*/product-previews
        methods: POST, GET
      # products-api
#      - url: /*/*/*/products/{externalId}
#        methods: GET
      - url: /*/*/*/products/{externalId}
        methods: GET
      # upload-api
      - url: /*/*/*/files
        methods: POST, GET, DELETE

logging:
  level:
    org: INFO