server:
  port: 8083

spring:
  application:
    name: review-service
    url: /public/api/v1
  jackson:
    serialization:
      fail-on-empty-beans: false
  config:
    import: "optional:configserver:"
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:navvrks9}
    driver-class-name: org.postgresql.Driver