name: Build Action

on:
  pull_request:
    branches:
      - develop
      - develop/*

jobs:
  build-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'
          cache: 'gradle'
      - run: ./gradlew clean build --no-daemon

