name: review-service ci/cd pipeline

env:
  USERNAME: github-actions
  USER_EMAIL: actions@mail.com
  SERVICE_NAME: review-service

on:
  pull_request:
    branches:
      - develop
    paths:
      - 'review-service/**'
  push:
    branches:
      - develop

jobs:
  build:
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    steps:
      - name: Download repo
        uses: actions/checkout@v3

      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto' #за семью
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build
        run: ./gradlew :${{ env.SERVICE_NAME }}:clean :${{ env.SERVICE_NAME }}:build

      - name: Generate JaCoCo report
        run: ./gradlew :${{ env.SERVICE_NAME }}:jacocoTestReport

      - name: Verify test coverage
        run: ./gradlew :${{ env.SERVICE_NAME }}:jacocoTestCoverageVerification

  deploy:
    if: ${{ github.event_name == 'push' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'corretto' #за брата
          java-version: '17'

      - name: Setup gradle
        uses: gradle/gradle-build-action@v2

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build and publish image
        run: ./gradlew :${{ env.SERVICE_NAME }}:jib

      - name: Executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SECRET_HOST }}
          username: ${{ secrets.SECRET_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SECRET_PORT }}
          script: ansible-playbook -i /home/support/ansible/hosts.txt /home/support/ansible/docker/${{ env.SERVICE_NAME }}/replace-container.yaml