version: "3.9"
services:
  user-info:
    container_name: yandex-market-user-info
    image: yandex-market/user-info:0.0.1-SNAPSHOT
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/test2
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin
      SPRING_JPA_HIBERNATE_DDL_AUTO: validate
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
      SPRING_DATA_REDIS_PASSWORD: password
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis

  postgres:
    container_name: postgres-shops
    image: postgres:15.1-alpine
    environment:
      POSTGRES_DB: test2
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      PGDATA: /data/postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    container_name: pgadmin-ui
    image: dpage/pgadmin4:6.17
    environment:
      PGADMIN_DEFAULT_EMAIL: pdfmain.user@gmail.com
      PGADMIN_DEFAULT_PASSWORD: password123
    volumes:
      - ./pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"

  redis:
    container_name: yandex-marker-redis
    hostname: redis
    image: redis
    ports:
      - "6379:6379"

  redis-commander:
    container_name: yandex-marker-redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"


volumes:
  pgdata:
  pgadmin:





